Repository labseu2-niyon/frontend, pull requests merged in 2019-09, with the labels that each got.

#35 Add Autocomplete
  .babelrc
  .eslintrc.json
  components/auth/Email.jsx
  components/auth/Location.jsx
  components/auth/ProfileInfo.jsx
  components/auth/Social.jsx
  next.config.js
  package-lock.json
  package.json
  pages/_document.js
  redux/actions/authActions.js
Labels: enhancement

#48 Ft/nprogess
  components/auth/Social.jsx
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  static/nprogrss.css
Labels: enhancement

#62 Adapt profile picture to fit in a circle
  components/explore/ExploreCard.jsx
  components/profile/PhotoSection.jsx
  components/~common/Avatar.jsx
Labels: bug

#73 Add profile picture placeholder
  components/Navigation.jsx
  components/explore/ExploreCard.jsx
  components/profile/PhotoSection.jsx
  lib/utils.js
  static/profile-placeholder.svg
Labels: bug

#79 Fix/signup url
  components/auth/Login.jsx
  components/auth/SignUp.jsx
Labels: bug, wip

#70 Feature: Socket.io (PP: Sorin, Vin, Delba)
  components/ChatData.jsx
  components/Navigation.jsx
  components/chat/ChatLayout.jsx
  components/chat/ChatMessage.jsx
  components/chat/Comment.jsx
  components/chat/Messages.jsx
  components/chat/User.jsx
  components/chat/UserList.jsx
  components/explore/Explore.jsx
  components/head.js
  lib/withAuth.js
  lib/withReduxStore.js
  package-lock.json
  package.json
  pages/chat.js
  pages/chat/[username].js
  pages/index.js
  redux/actions/authActions.js
  redux/actions/userActions.js
  redux/reducers/authReducer.js
Labels: wip
